
t = {
	"A": "La vita è un'avventura inaspettata.",
	"B": "Il silenzio parla più forte delle parole.",
	"C": "L'arte di vivere consiste nell'imparare a lasciare andare.",
	"Tempo": "Il tempo è un'illusione che sfida la logica.",
	"Spirito": "Lo spirito umano è un universo di possibilità.",
	"Onda": "Come un'onda, le emozioni vanno e vengono.",
	"archivio": "Voce di prova per testare il menu.",
	"archivio2025": "Altra Voce di prova per testare il menu.",
	"Arcobaleno": "L'arcobaleno è la promessa di speranza dopo la tempesta.",
	"Viaggio": "Ogni viaggio inizia con un passo incerto.",
	"Sogno": "I sogni sono le chiavi che aprono le porte dell'immaginazione.",
	"Stella": "Una stella brilla nell'oscurità per guidare chi cerca.",
	"Desiderio": "Il desiderio è il motore che accende il cuore.",
	"Silenzio": "Nel silenzio, le verità più profonde si svelano.",
	"Melodia": "La melodia della vita risuona in ogni angolo dell'anima.",
	"Vento": "Il vento porta con sé storie dimenticate.",
	"Speranza": "La speranza illumina anche i giorni più bui.",
	"Fiamma": "Una fiamma ardente sfida la notte più fredda.",
	"Riflesso": "Il riflesso dell'acqua racconta storie antiche.",
	"Nebbia": "Tra la nebbia, il mistero si nasconde.",
	"Eco": "L'eco delle parole non dette risuona lontano.",
	"Orologio": "L'orologio segna il ritmo inarrestabile del destino.",
	"Sguardo": "Un solo sguardo può cambiare il corso di una vita.",
	"Parola": "La parola ha il potere di guarire o ferire.",
	"Pensiero": "Il pensiero libero è la scintilla della creatività.",
	"Risata": "Una risata sincera è una medicina per l'anima.",
	"Deserto": "Il deserto custodisce segreti di mondi antichi.",
	"Foresta": "Nella foresta, ogni albero racconta una storia.",
	"Mare": "Il mare è un abisso di emozioni senza confini.",
	"Fiume": "Il fiume scorre, portando via ricordi e speranze.",
	"Montagna": "La montagna sfida chi osa guardarla con stupore.",
	"Luna": "La luna illumina la via dei viaggiatori notturni.",
	"Sole": "Il sole riscalda il cuore in ogni alba.",
	"Pioggia": "La pioggia rinfresca la terra assetata.",
	"Tempesta": "La tempesta purifica l'anima con la sua forza.",
	"Arcano": "Il mistero arcano invita a scoprire l'ignoto.",
	"Vita": "La vita è un mosaico di momenti preziosi.",
	"Infinito": "L'infinito si svela nelle piccole cose quotidiane.",
	"Origine": "L'origine di ogni sogno è un seme di speranza.",
	"Destino": "Il destino intreccia le storie degli esseri viventi.",
	"EcoInfinito": "L'eco infinito del passato risuona nel presente.",
	"Ricordo": "Ogni ricordo è una pagina scritta nel libro della vita."
}
s = menu(t, show=True, keyslist=True, full_keyslist=False, pager=5, show_on_filter=True)
print(f"\nScelta: {s}")
